// Generated by scripts/generate-starter-racing-track.mjs — do not edit by hand.
// Source: _tmp_racing/Starter-Kit-Racing-main/scenes/main.tscn (GridMap cells)

export type StarterRacingCell = {
  gx: number;
  gy: number;
  gz: number;
  item: number;
  ortho: number;
};

/** Decoded GridMap cells (154 instances). */
export const STARTER_RACING_GRID_CELLS: readonly StarterRacingCell[] = [
  {
    "gx": -3,
    "gy": 0,
    "gz": 0,
    "item": 0,
    "ortho": 0
  },
  {
    "gx": -3,
    "gy": 0,
    "gz": 1,
    "item": 1,
    "ortho": 22
  },
  {
    "gx": -3,
    "gy": 0,
    "gz": 2,
    "item": 1,
    "ortho": 16
  },
  {
    "gx": 1,
    "gy": 0,
    "gz": -1,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 1,
    "gy": 0,
    "gz": 0,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 1,
    "gy": 0,
    "gz": 1,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 1,
    "gy": 0,
    "gz": 2,
    "item": 0,
    "ortho": 0
  },
  {
    "gx": 1,
    "gy": 0,
    "gz": 3,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 0,
    "gy": 0,
    "gz": 3,
    "item": 0,
    "ortho": 0
  },
  {
    "gx": -1,
    "gy": 0,
    "gz": 3,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -2,
    "gy": 0,
    "gz": 3,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -3,
    "gy": 0,
    "gz": 3,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -4,
    "gy": 0,
    "gz": -2,
    "item": 2,
    "ortho": 10
  },
  {
    "gx": -4,
    "gy": 0,
    "gz": -1,
    "item": 0,
    "ortho": 0
  },
  {
    "gx": -4,
    "gy": 0,
    "gz": -4,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -4,
    "gy": 0,
    "gz": -3,
    "item": 1,
    "ortho": 16
  },
  {
    "gx": -3,
    "gy": 0,
    "gz": -4,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -2,
    "gy": 0,
    "gz": -4,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -1,
    "gy": 0,
    "gz": -4,
    "item": 2,
    "ortho": 22
  },
  {
    "gx": 0,
    "gy": 0,
    "gz": -4,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 1,
    "gy": 0,
    "gz": -4,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 1,
    "gy": 0,
    "gz": -3,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 1,
    "gy": 0,
    "gz": -2,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -4,
    "gy": 0,
    "gz": 0,
    "item": 1,
    "ortho": 16
  },
  {
    "gx": -4,
    "gy": 0,
    "gz": 1,
    "item": 1,
    "ortho": 16
  },
  {
    "gx": -4,
    "gy": 0,
    "gz": 2,
    "item": 0,
    "ortho": 16
  },
  {
    "gx": -4,
    "gy": 0,
    "gz": 3,
    "item": 0,
    "ortho": 0
  },
  {
    "gx": -4,
    "gy": 0,
    "gz": 4,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -3,
    "gy": 0,
    "gz": 4,
    "item": 0,
    "ortho": 0
  },
  {
    "gx": -2,
    "gy": 0,
    "gz": 4,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -1,
    "gy": 0,
    "gz": 4,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 0,
    "gy": 0,
    "gz": 4,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 1,
    "gy": 0,
    "gz": 4,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 2,
    "gy": 0,
    "gz": 4,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 2,
    "gy": 0,
    "gz": 3,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 2,
    "gy": 0,
    "gz": 2,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 2,
    "gy": 0,
    "gz": 1,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 2,
    "gy": 0,
    "gz": 0,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 2,
    "gy": 0,
    "gz": -1,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 2,
    "gy": 0,
    "gz": -2,
    "item": 0,
    "ortho": 0
  },
  {
    "gx": 2,
    "gy": 0,
    "gz": -3,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 2,
    "gy": 0,
    "gz": -4,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 2,
    "gy": 0,
    "gz": -5,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 1,
    "gy": 0,
    "gz": -5,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 0,
    "gy": 0,
    "gz": -5,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 0,
    "gy": 0,
    "gz": -6,
    "item": 0,
    "ortho": 0
  },
  {
    "gx": -1,
    "gy": 0,
    "gz": -6,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -1,
    "gy": 0,
    "gz": -5,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -2,
    "gy": 0,
    "gz": -5,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -3,
    "gy": 0,
    "gz": -5,
    "item": 0,
    "ortho": 0
  },
  {
    "gx": -4,
    "gy": 0,
    "gz": -5,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -4,
    "gy": 0,
    "gz": -6,
    "item": 0,
    "ortho": 0
  },
  {
    "gx": -3,
    "gy": 0,
    "gz": -6,
    "item": 0,
    "ortho": 0
  },
  {
    "gx": -2,
    "gy": 0,
    "gz": -6,
    "item": 0,
    "ortho": 0
  },
  {
    "gx": 1,
    "gy": 0,
    "gz": -6,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 2,
    "gy": 0,
    "gz": -6,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -5,
    "gy": 0,
    "gz": 4,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -5,
    "gy": 0,
    "gz": 3,
    "item": 0,
    "ortho": 0
  },
  {
    "gx": -5,
    "gy": 0,
    "gz": 2,
    "item": 0,
    "ortho": 16
  },
  {
    "gx": -5,
    "gy": 0,
    "gz": 1,
    "item": 0,
    "ortho": 16
  },
  {
    "gx": -5,
    "gy": 0,
    "gz": 0,
    "item": 1,
    "ortho": 16
  },
  {
    "gx": -5,
    "gy": 0,
    "gz": -1,
    "item": 0,
    "ortho": 16
  },
  {
    "gx": -5,
    "gy": 0,
    "gz": -2,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -5,
    "gy": 0,
    "gz": -3,
    "item": 0,
    "ortho": 16
  },
  {
    "gx": -5,
    "gy": 0,
    "gz": -4,
    "item": 0,
    "ortho": 0
  },
  {
    "gx": -5,
    "gy": 0,
    "gz": -5,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -5,
    "gy": 0,
    "gz": -6,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -6,
    "gy": 0,
    "gz": -6,
    "item": 0,
    "ortho": 0
  },
  {
    "gx": -6,
    "gy": 0,
    "gz": -5,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -6,
    "gy": 0,
    "gz": -4,
    "item": 0,
    "ortho": 0
  },
  {
    "gx": -6,
    "gy": 0,
    "gz": -3,
    "item": 0,
    "ortho": 16
  },
  {
    "gx": -6,
    "gy": 0,
    "gz": -2,
    "item": 0,
    "ortho": 16
  },
  {
    "gx": -6,
    "gy": 0,
    "gz": -1,
    "item": 0,
    "ortho": 16
  },
  {
    "gx": -6,
    "gy": 0,
    "gz": 0,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -6,
    "gy": 0,
    "gz": 1,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -6,
    "gy": 0,
    "gz": 2,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -6,
    "gy": 0,
    "gz": 3,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -6,
    "gy": 0,
    "gz": 4,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -6,
    "gy": 0,
    "gz": -7,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -5,
    "gy": 0,
    "gz": -7,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -4,
    "gy": 0,
    "gz": -7,
    "item": 0,
    "ortho": 0
  },
  {
    "gx": -3,
    "gy": 0,
    "gz": -7,
    "item": 0,
    "ortho": 0
  },
  {
    "gx": -2,
    "gy": 0,
    "gz": -7,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -1,
    "gy": 0,
    "gz": -7,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 0,
    "gy": 0,
    "gz": -7,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 1,
    "gy": 0,
    "gz": -7,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 2,
    "gy": 0,
    "gz": -7,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 2,
    "gy": 0,
    "gz": -8,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 1,
    "gy": 0,
    "gz": -8,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 0,
    "gy": 0,
    "gz": -8,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -1,
    "gy": 0,
    "gz": -8,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -2,
    "gy": 0,
    "gz": -8,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -3,
    "gy": 0,
    "gz": -8,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -4,
    "gy": 0,
    "gz": -8,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -5,
    "gy": 0,
    "gz": -8,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -6,
    "gy": 0,
    "gz": -8,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -7,
    "gy": 0,
    "gz": -8,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -7,
    "gy": 0,
    "gz": -7,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -7,
    "gy": 0,
    "gz": -6,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -7,
    "gy": 0,
    "gz": -5,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -7,
    "gy": 0,
    "gz": -4,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -7,
    "gy": 0,
    "gz": -3,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -7,
    "gy": 0,
    "gz": -2,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -7,
    "gy": 0,
    "gz": -1,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -7,
    "gy": 0,
    "gz": 0,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -7,
    "gy": 0,
    "gz": 1,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -7,
    "gy": 0,
    "gz": 2,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -7,
    "gy": 0,
    "gz": 3,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -7,
    "gy": 0,
    "gz": 4,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -8,
    "gy": 0,
    "gz": 4,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -8,
    "gy": 0,
    "gz": 3,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -8,
    "gy": 0,
    "gz": 2,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -8,
    "gy": 0,
    "gz": 1,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -8,
    "gy": 0,
    "gz": 0,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -8,
    "gy": 0,
    "gz": -1,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -8,
    "gy": 0,
    "gz": -2,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -8,
    "gy": 0,
    "gz": -3,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -8,
    "gy": 0,
    "gz": -4,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -8,
    "gy": 0,
    "gz": -5,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -8,
    "gy": 0,
    "gz": -6,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -8,
    "gy": 0,
    "gz": -7,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -8,
    "gy": 0,
    "gz": -8,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -8,
    "gy": 0,
    "gz": -9,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -7,
    "gy": 0,
    "gz": -9,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -6,
    "gy": 0,
    "gz": -9,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -5,
    "gy": 0,
    "gz": -9,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -4,
    "gy": 0,
    "gz": -9,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -3,
    "gy": 0,
    "gz": -9,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -2,
    "gy": 0,
    "gz": -9,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -1,
    "gy": 0,
    "gz": -9,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 0,
    "gy": 0,
    "gz": -9,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 1,
    "gy": 0,
    "gz": -9,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": 2,
    "gy": 0,
    "gz": -9,
    "item": 1,
    "ortho": 10
  },
  {
    "gx": -1,
    "gy": 0,
    "gz": -1,
    "item": 1,
    "ortho": 22
  },
  {
    "gx": -1,
    "gy": 0,
    "gz": -2,
    "item": 1,
    "ortho": 22
  },
  {
    "gx": -2,
    "gy": 0,
    "gz": -2,
    "item": 1,
    "ortho": 22
  },
  {
    "gx": -1,
    "gy": 0,
    "gz": 1,
    "item": 2,
    "ortho": 22
  },
  {
    "gx": -1,
    "gy": 0,
    "gz": 0,
    "item": 1,
    "ortho": 22
  },
  {
    "gx": 0,
    "gy": 0,
    "gz": 0,
    "item": 4,
    "ortho": 0
  },
  {
    "gx": 0,
    "gy": 0,
    "gz": -1,
    "item": 6,
    "ortho": 0
  },
  {
    "gx": -2,
    "gy": 0,
    "gz": 0,
    "item": 6,
    "ortho": 10
  },
  {
    "gx": -2,
    "gy": 0,
    "gz": 1,
    "item": 6,
    "ortho": 10
  },
  {
    "gx": -3,
    "gy": 0,
    "gz": -2,
    "item": 6,
    "ortho": 0
  },
  {
    "gx": -2,
    "gy": 0,
    "gz": -3,
    "item": 6,
    "ortho": 22
  },
  {
    "gx": -1,
    "gy": 0,
    "gz": -3,
    "item": 6,
    "ortho": 22
  },
  {
    "gx": 0,
    "gy": 0,
    "gz": -2,
    "item": 6,
    "ortho": 0
  },
  {
    "gx": -1,
    "gy": 0,
    "gz": 2,
    "item": 6,
    "ortho": 16
  },
  {
    "gx": -3,
    "gy": 0,
    "gz": -3,
    "item": 3,
    "ortho": 16
  },
  {
    "gx": -3,
    "gy": 0,
    "gz": -1,
    "item": 3,
    "ortho": 10
  },
  {
    "gx": -2,
    "gy": 0,
    "gz": -1,
    "item": 3,
    "ortho": 0
  },
  {
    "gx": 0,
    "gy": 0,
    "gz": -3,
    "item": 3,
    "ortho": 0
  },
  {
    "gx": 0,
    "gy": 0,
    "gz": 2,
    "item": 3,
    "ortho": 22
  },
  {
    "gx": -2,
    "gy": 0,
    "gz": 2,
    "item": 3,
    "ortho": 10
  },
  {
    "gx": 0,
    "gy": 0,
    "gz": 1,
    "item": 6,
    "ortho": 0
  }
] as const;

/** Axis-aligned bounds in grid coordinates (for mapHalf estimate). */
export const STARTER_RACING_GRID_BOUNDS = {
  minX: -8,
  maxX: 2,
  minZ: -9,
  maxZ: 4,
} as const;
